BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('admin', 'user');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'word_type_enum') THEN
    CREATE TYPE word_type_enum AS ENUM ('noun', 'verb', 'adj', 'adv', 'phrase', 'other');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(100) NOT NULL,
  slug varchar(100) NOT NULL UNIQUE,
  description varchar(500),
  icon varchar(50),
  sort_order integer DEFAULT 0,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL UNIQUE,
  email varchar(100) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  full_name varchar(100),
  avatar_url varchar(500),
  role user_role DEFAULT 'user',
  hsk_level smallint DEFAULT 1,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  last_login timestamp,
  is_active smallint DEFAULT 1,
  email_verified smallint DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_role ON users(role);

CREATE TABLE IF NOT EXISTS videos (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(200) NOT NULL,
  title_cn varchar(200),
  description varchar(1000),
  category_id integer REFERENCES categories(id) ON DELETE SET NULL,
  hsk_level smallint NOT NULL DEFAULT 1,
  language_track varchar(16) NOT NULL DEFAULT 'chinese',
  video_url varchar(500) NOT NULL,
  thumbnail_url varchar(500),
  subtitle_cn_url varchar(500),
  subtitle_vi_url varchar(500),
  subtitle_pinyin_url varchar(500),
  duration integer DEFAULT 0,
  difficulty_score numeric(3,2) DEFAULT 1.00,
  view_count integer DEFAULT 0,
  like_count integer DEFAULT 0,
  is_published smallint DEFAULT 0,
  is_free smallint DEFAULT 1,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  published_at timestamp,
  created_by integer REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_hsk ON videos(hsk_level);
CREATE INDEX IF NOT EXISTS idx_videos_language_track ON videos(language_track);
CREATE INDEX IF NOT EXISTS idx_category ON videos(category_id);
CREATE INDEX IF NOT EXISTS idx_published ON videos(is_published);
CREATE INDEX IF NOT EXISTS idx_created_by ON videos(created_by);

CREATE TABLE IF NOT EXISTS video_vocabulary (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id integer NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  word_cn varchar(50) NOT NULL,
  pinyin varchar(100),
  meaning_vi varchar(200),
  word_type word_type_enum DEFAULT 'other',
  hsk_level smallint,
  example_sentence varchar(500),
  timestamp_start numeric(10,3),
  sort_order integer DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_video_vocabulary_video ON video_vocabulary(video_id);
CREATE INDEX IF NOT EXISTS idx_video_vocabulary_word ON video_vocabulary(word_cn);

CREATE TABLE IF NOT EXISTS study_streaks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  study_date date NOT NULL,
  minutes_studied integer DEFAULT 0,
  videos_watched integer DEFAULT 0,
  words_learned integer DEFAULT 0,
  CONSTRAINT unique_user_date UNIQUE (user_id, study_date)
);

CREATE INDEX IF NOT EXISTS idx_user_date ON study_streaks(user_id, study_date);

CREATE TABLE IF NOT EXISTS subtitle_clicks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer REFERENCES users(id) ON DELETE SET NULL,
  video_id integer NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  clicked_text varchar(50) NOT NULL,
  timestamp_in_video numeric(10,3),
  clicked_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_subtitle_clicks_user ON subtitle_clicks(user_id);
CREATE INDEX IF NOT EXISTS idx_subtitle_clicks_video ON subtitle_clicks(video_id);
CREATE INDEX IF NOT EXISTS idx_subtitle_clicks_text ON subtitle_clicks(clicked_text);

CREATE TABLE IF NOT EXISTS user_progress (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  video_id integer NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  watched_seconds integer DEFAULT 0,
  last_position numeric(10,3) DEFAULT 0.000,
  watch_percentage numeric(5,2) DEFAULT 0.00,
  is_completed smallint DEFAULT 0,
  completed_at timestamp,
  shadowing_count integer DEFAULT 0,
  loop_count integer DEFAULT 0,
  first_watched_at timestamp DEFAULT CURRENT_TIMESTAMP,
  last_watched_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_user_video UNIQUE (user_id, video_id)
);

CREATE INDEX IF NOT EXISTS idx_user_progress_user ON user_progress(user_id);
CREATE INDEX IF NOT EXISTS idx_user_progress_video ON user_progress(video_id);

CREATE TABLE IF NOT EXISTS user_saved_words (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  vocabulary_id integer REFERENCES video_vocabulary(id) ON DELETE SET NULL,
  custom_word_cn varchar(50),
  custom_pinyin varchar(100),
  custom_meaning varchar(200),
  mastery_level smallint DEFAULT 0,
  review_count integer DEFAULT 0,
  last_reviewed_at timestamp,
  next_review_at timestamp,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_user_saved_words_vocab ON user_saved_words(vocabulary_id);
CREATE INDEX IF NOT EXISTS idx_user_saved_words_user ON user_saved_words(user_id);
CREATE INDEX IF NOT EXISTS idx_user_saved_words_review ON user_saved_words(next_review_at);

CREATE TABLE IF NOT EXISTS user_sessions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  session_token varchar(255) NOT NULL UNIQUE,
  ip_address varchar(45),
  user_agent varchar(500),
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp NOT NULL,
  is_valid smallint DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_user_sessions_token ON user_sessions(session_token);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user ON user_sessions(user_id);

CREATE TABLE IF NOT EXISTS video_slang (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id integer NOT NULL,
  word_cn varchar(120) NOT NULL,
  pinyin varchar(120),
  meaning_vi text,
  tone_note text,
  usage_note text,
  example_cn_1 text,
  example_pinyin_1 text,
  example_vi_1 text,
  example_cn_2 text,
  example_pinyin_2 text,
  example_vi_2 text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_video_slang_video ON video_slang(video_id);
CREATE INDEX IF NOT EXISTS idx_video_slang_sort ON video_slang(video_id, sort_order);

CREATE TABLE IF NOT EXISTS subtitles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id integer NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  start_time numeric(10,3),
  end_time numeric(10,3),
  en_text text,
  vn_text text,
  word_timings text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_subtitles_video ON subtitles(video_id);
CREATE INDEX IF NOT EXISTS idx_subtitles_video_time ON subtitles(video_id, start_time);


COMMIT;

