BEGIN;

-- 1) videos.language_track used by current backend/frontend filters
ALTER TABLE videos
  ADD COLUMN IF NOT EXISTS language_track varchar(16);

UPDATE videos
SET language_track = 'chinese'
WHERE language_track IS NULL OR TRIM(language_track) = '';

ALTER TABLE videos
  ALTER COLUMN language_track SET DEFAULT 'chinese';

ALTER TABLE videos
  ALTER COLUMN language_track SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_videos_language_track ON videos(language_track);

-- 2) subtitles table used by YouTube translation pipeline and player timeline
CREATE TABLE IF NOT EXISTS subtitles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id integer NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  start_time numeric(10,3),
  end_time numeric(10,3),
  en_text text,
  vn_text text,
  word_timings text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP
);

-- In case subtitles table already existed from custom script without these columns
ALTER TABLE subtitles ADD COLUMN IF NOT EXISTS start_time numeric(10,3);
ALTER TABLE subtitles ADD COLUMN IF NOT EXISTS end_time numeric(10,3);
ALTER TABLE subtitles ADD COLUMN IF NOT EXISTS en_text text;
ALTER TABLE subtitles ADD COLUMN IF NOT EXISTS vn_text text;
ALTER TABLE subtitles ADD COLUMN IF NOT EXISTS word_timings text;
ALTER TABLE subtitles ADD COLUMN IF NOT EXISTS created_at timestamp DEFAULT CURRENT_TIMESTAMP;

-- Add FK only if missing. NOT VALID avoids failing on legacy orphan rows.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'subtitles_video_id_fkey'
  ) THEN
    ALTER TABLE subtitles
      ADD CONSTRAINT subtitles_video_id_fkey
      FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_subtitles_video ON subtitles(video_id);
CREATE INDEX IF NOT EXISTS idx_subtitles_video_time ON subtitles(video_id, start_time);

COMMIT;
